### PR TITLE
ping endpoint added to proxy

### LINKED ISSUE #33: Conan Proxy Repository does not work
I am using OSS 3.14.0-04 and  Nexus-Repository-Conan 0.0.3.

I created a 'Nexus Proxy repository' that refers to the conan center repository 'https://conan.bintray.com/'

`conan-center: https://nexus.mycompany.com/repository/conan-center/ [Verify SSL: False]`

Unfortuatelly I am not able to connect to the proxy due to the following error:

```
conan user myuser -p mypassword -r conan-center
ERROR: Not implemented endpoint. [Remote: conan-center]
```

Hosted repositories work as expected.

### PR DESCRIPTION
**Pull request by doddi**
Looks like the introduction of the ping endpoint for new clients broke the proxy

* Fixes #33

### CODE REVIEW

File: src/main/java/org/sonatype/repository/conan/internal/proxy/matcher/ConanMatcher.groovy [hunk 1]
```diff
@@ -119,6 +121,18 @@ class ConanMatcher
...
   }
 
+  /**
+   * Matches on ping endpoint
+   */
+  static Builder ping() {
+    new Builder().matcher(
+        and(
+            new ActionMatcher(GET),
+            new TokenMatcher(PING)
```
Comment (DarthHater) [inline src/main/java/org/sonatype/repository/conan/internal/proxy/matcher/ConanMatcher.groovy]: Suggestion: You probably don't need a TokenMatcher here, and might be able to get away with a LiteralMatcher.

Comment (doddi) [reply src/main/java/org/sonatype/repository/conan/internal/proxy/matcher/ConanMatcher.groovy]: https://github.com/sonatype-nexus-community/nexus-repository-conan/pull/45/commits/5585a36ecdceec2551ad34bf496df0fe00be97fd
