### PR TITLE
remap download_url to GAV

### LINKED ISSUE #30: Download of hosted packages does not work due to wrong path
* **What are you trying to do?**
Use the hosted repository "the conan way" by uploading and downloading packages.

## Reproduction Steps
- 2 repositories
  1. _conan_ (hosted)
  2. _conan-proxy_ (Proxy of conan-central)
- minimal hello world app testlib
- Upload to to _conan_  with `conan upload -r conan testlib/1.0/myuser/testing --all` ✅ 
   It shows up in nexus
- Try to use it in simple testing project.
  - requirements file: `testlib/1.0/myuser/testing`
  - install requirements with `conan install` ❌ `ERROR: testlib/1.0/myuser/testing was not found in remote 'conan'`
- Try to use a package from proxy
  - requirements file: `Poco/1.8.1@pocoproject/stable`
  - install requirements with `conan install` ✅ 
    - files are downloaded to proxy repo, shows up in the same way as testlib in _conan_ repository
    - packages are downloaded as well

We were suspicios because in nexus ui the path is inverted in the tree (pocoproject ➡️ Poco ➡️ 1.8.1 ➡️ ...) so we try it again and it works the second time too without a redownload from conan-central.

### PR DESCRIPTION
**Pull request by doddi**
The download url paths need to be remapped to GAV order

* Fixes #30

### CODE REVIEW

File: src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedFacet.java [hunk 1]
```diff
@@ -213,12 +213,15 @@ private Content saveAsset(final StorageTx tx,
 
   /**
    * Services the download_urls endpoint for root and package data
+   * @param path path as GAV
```
Comment (jlstephens89) [inline src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedFacet.java]: Trivial: path path is not necessary

Comment (jlstephens89) [reply src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedFacet.java]: Maybe rename this to gavPath?

Comment (jlstephens89) [reply src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedFacet.java]: I would like a comment to explain that artifacts are stored with one path and fetched with another + the reason why (other endpoints use GAV). Weird that the Conan developers decided to be inconsistent here - if you've created an issue with conan IO maybe link it here.

File: src/main/java/org/sonatype/repository/conan/internal/hosted/HostedHandlers.java [hunk 2]
```diff
@@ -99,10 +99,15 @@ private String getAssetPath(final State state, final ConanCoords coord) {
...
   }
 
-  final Handler downloadUrl = context ->
-      context.getRepository()
-          .facet(ConanHostedFacet.class)
-          .getDownloadUrl(context);
+  final Handler downloadUrl = context -> {
+    State state = context.getAttributes().require(State.class);
+    ConanCoords coord = convertFromState(state);
+    String path = getAssetPath(state, coord) + "/download_urls";
```
Comment (jlstephens89) [inline src/main/java/org/sonatype/repository/conan/internal/hosted/HostedHandlers.java]: Trivial: state is not used in getAssetPath so can be removed
